In [1]:
from feed import Feed
feed=Feed('k26_static')
stop20=feed.DescribeForFlag(20)
print(stop20)

Stop name 13    Магазин "Аквариум"
Serves 5 routes: [6, 1, 2, 10, 44]
{'bus_6': ['06:48:00', '21:03:00'], 'bus_1': ['06:10:00', '23:05:00'], 'bus_2': ['06:55:00', '23:35:00'], 'bus_10': ['06:05:00', '23:15:00'], 'bus_44': ['06:34:00', '22:56:00']}

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,route_id,service_id,trip_headsign,direction_id,block_id,shape_id
0,bus_1_dir1_05_59_winter_weekday,06:10:00,06:10:00,20,10,NaN,NaN,NaN,NaN,bus_1,winter_weekday,Ленина 75,0,bus_1_veh1,bus_1_dir1_shape
1,bus_1_dir1_06_29_winter_weekday,06:40:00,06:40:00,20,10,NaN,NaN,NaN,NaN,bus_1,winter_weekday,Ленина 75,0,bus_1_veh1,bus_1_dir1_shape
2,bus_1_dir1_06_49_winter_weekday,07:00:00,07:00:00,20,10,NaN,NaN,NaN,NaN,bus_1,winter_weekday,Ленина 75,0,bus_1_veh1,bus_1_dir1_shape
3,bus_1_dir1_07_09_winter_weekday,07:20:00,07:20:00,20,10,NaN,NaN,NaN,NaN,bus_1,winter_weekday,Ленина 75,0,bus_1_veh1,bus_1_dir1_shape
4,bus_1_dir1_07_29_winter_weekday,07:40:00,07:40:00,20,10,NaN,NaN,NaN,NaN,bus_1,winter_weekday,Ленина 75,0,bus_1_veh1,bus_1_dir1_shape
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,bus_6_dir0_18_00_0,18:33:00,18:33:00,20,21,NaN,NaN,NaN,NaN,bus_6,0,Лукаши,1,bus_6_veh0,bus_6_dir0_shape
498,bus_6_dir0_18_20_0,18:53:00,18:53:00,20,21,NaN,NaN,NaN,NaN,bus_6,0,Лукаши,1,bus_6_veh0,bus_6_dir0_shape
499,bus_6_dir0_19_00_0,19:33:00,19:33:00,20,21,NaN,NaN,NaN,NaN,bus_6,0,Лукаши,1,bus_6_veh0,bus_6_dir0_shape
500,bus_6_dir0_19_40_0,20:13:00,20:13:00,20,21,NaN,NaN,NaN,NaN,bus_6,0,Лукаши,1,bus_6_veh0,bus_6_dir0_shape
501,bus_6_dir0_20_30_0,21:03:00,21:03:00,20,21,NaN,NaN,NaN,NaN,bus_6,0,Лукаши,1,bus_6_veh0,bus_6_dir0_shape